spring:
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 816bd85980092eeaa14987da42be1788
            client-secret: uMNW93SA6HGqnY09VuAaxrsfczMODca0
            client-name: kakao-login
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:3000/auth/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bread?&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  auth:
    jwt:
      secret-key: 2d4e6f8g0h1i3j5k7l9m2n4p6q8r0s2t4v6w8x0z2b4d6f8h0j2l4m6n8p0r2t4v6x8z1a3c5e7g9i
      access-token-expiry: 32140800
      refresh-token-expiry: 1209600

cloud:
  aws:
    credentials:
      access-key: AKIA6PBGC3B35AUMAEIJ
      secret-key: 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
    s3:
      bucket: palgona
    region:
      static: ap-northeast-2
    stack:
      auto: false

s3:
  base:
    url: https://palgona.s3.ap-northeast-2.amazonaws.com/

app:
  user:
    managerId: qoraudrb123@gmail.com
    apiKey: 070b502516804bcc948145f71d0ea285
  admin:
    userId: adminBread@ssafy.co.kr
    userKey: aef9533e-ef4d-417a-a173-fdc01bbb9cae
    account : 0017352920503544

ai:
  server:
    ip: localhost
    port: 8002
    port2: 8001